document:
  xmlns: 'urn:iso:std:iso:20022:tech:xsd:camt.054.001.04'
  xmlns_xsi: 'http://www.w3.org/2001/XMLSchema-instance'
  xsi_schemaLocation: 'urn:iso:std:iso:20022:tech:xsd:camt.054.001.04 camt.054.001.04.xsd'

acct:
  iban: 'DE52430609677023575300'
  ccy: 'CHF'
  ownr:
    nm: 'My NPO eV'
  credttm: '2023-12-31T13:21:00'
  svcr:
    fin_instn_id:
      bic: 'GENODEM1GLS'
      nm: 'GLS Gemeinschaftsbank eG'
      othr:
        id: 'DE 12349987'
        issr: 'UmsStId'
BkTxCd:
  Domn:
    Cd: 'PMNT'
    Fmly:
      Cd: 'IDDT'
      SubFmlyCd: 'PMDD'